### ISSUE TITLE
Redmine - Issue: Search by multiple status

### ISSUE THREAD

**Issue by Pinolo** [sparkfabrik/sparktool#12]
Sometimes it is quite useful to search for multiple status, fe:

`% spark redmine:search --sprint="SPRINT-30" --status="new, in progress" --subject="EE"`

In order to find "new and in-progress" issues.

---

@marcofrattola: 
A simple syntax like ?status_id=8&status_id=10 would have been great, by the way Redmine API is not uniformly implemented: multiple query values are implemented on some parameters but not on status_id

I found on StackOverflow this answer http://stackoverflow.com/a/18358659 about an undocumented way of calling issue API with multiple values:

for instance you can try with postman such a GET call: https://projects.agavee.com/issues.json?project_id=154&f[]=status_id&op[status_id]==&v[status_id][]=10&v[status_id][]=8&sort=updated_on

Asked in php-redmine-api library issue too: https://github.com/kbsali/php-redmine-api/issues/127

Update: 
it seems that an alternative syntax by "|" is possible... (I tested, it seems working):

> that looks interesting @marcofrattola ,
> but i failed understand the logic of the arguments list of the example you found on stackoverflow?
> 
> It looks like this has been asked for a long time ago and Redmine's lead dev had a proposal : 
> http://www.redmine.org/issues/10828
> I'm not sure if it has been added to the api though... (would you mind checking? status_id=8|10) ?

from https://github.com/kbsali/php-redmine-api/issues/127#issuecomment-101047916

**Comment by vincenzodibiaggio** [comment]
https://github.com/sparkfabrik/sparktool/pull/29

**Comment by paolomainardi** [comment]
Merged!
