### ISSUE TITLE
Redmine - Git: Git branch name broken with quotes on subject

### ISSUE THREAD

**Issue by Pinolo** [sparkfabrik/sparktool#15]
Example: `EE-630 - Change the “Create a Meeting” and “Message” labels``

```
~/Projects/workspace/elite-exchange (develop :heavy_check_mark:) ᐅ spark redmine:git:branch 8790
Error: sed: RE error: illegal byte sequence
flags:FATAL the available getopt does not support spaces in options
```

**Comment by Pinolo** [comment]
The problem is with UTF-8 characters, not with quotes

**Comment by paolomainardi** [comment]
I suggest to strip out all chars out of A-Z-0-9 space.

**Comment by Pinolo** [comment]
Not replacing accented? e.g. "è" might become "e".
Besides, turns out it's a bug in our code, both git and git flow work fine with UTF-8 chars

**Comment by paolomainardi** [comment]
yes, replacing the accents too

**Comment by paolomainardi** [comment]
:+1: merged!
