### ISSUE TITLE
Make remine:git:branch command "issue title" agnostic

### ISSUE THREAD

**Issue by alessiopiazza** [sparkfabrik/sparktool#45]
Current remind:git:branch implementation requires a specific issue title:
STORY_PREFIX-STORY_CODE_ISSUE_ID - STORY_NAME
This pattern is not always available on every project. We should have a way to rely on a more generic pattern, creating a new branch with "REDMINE_ISSUE_NUMBER + REDMINE_ISSUE_TITLE"

**Comment by alessiopiazza** [comment]
We should also rely on custom fields instead of a "well formatted" title

**Comment by paolomainardi** [comment]
@alessiopiazza can i close this issue ?

**Comment by alessiopiazza** [comment]
Let me check if the branch structure definition is still necessary

**Comment by alessiopiazza** [comment]
I would say it's still necessary so we can close this issue
